version: "2"         # required to adjust maintainability checks
languages:
   JavaScript: true

checks:
  file-lines:
    enabled: false


exclude_paths:
 - "**/tests"
 - "**/tmp"
 - "**/node_modules/"
