name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:

  lint:
    name: "Lint"
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - uses: actions/cache@v2
      with:
        path: <%= yarn ? '${{ steps.yarn-cache-dir-path.outputs.dir }}' : '~/.npm' %>
        key: ${{ runner.os }}-modules-${{ hashFiles('<%= yarn ? '**/yarn.lock' : '**/package-lock.json' %>') }}
    - name: Install Dependencies
      run: <%= yarn ? 'yarn' : 'npm' %> install
    - name: Lint
      run: <%= yarn ? 'yarn' : 'npm run' %> lint

  floating:
    name: "Floating dependencies"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        try-scenario: 
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe
          - embroider-optimized
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - uses: actions/cache@v2
      with:
        path: <%= yarn ? '${{ steps.yarn-cache-dir-path.outputs.dir }}' : '~/.npm' %>
        key: ${{ runner.os }}-modules-${{ hashFiles('<%= yarn ? '**/yarn.lock' : '**/package-lock.json' %>') }}
    - name: Install Dependencies
      run: <%= yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
    - name: Run Tests
      run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
