---
language: node_js
node_js:
  - "6"

sudo: false
<% if (yarn) { %>
cache:
  yarn: true
  directories:
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - yarn test<% } else { %>
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - npm test<% } %>
