name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint

  basic-tests:
    name: "Basic Tests - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS, windows]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test

  tests:
    name: "Node ${{ matrix.node-version }} - ${{ matrix.os }} "
    runs-on: "${{ matrix.os }}-latest"

    needs: [linting, basic-tests]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu, windows]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: npm i -g npm@latest
      - run: pnpm install
      - run: pnpm --filter layer-gen run test:all
